// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pobddeahabrovgsxnbvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvYmRkZWFoYWJyb3Znc3huYnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzQzNTMsImV4cCI6MjA3NDU1MDM1M30.NxdTXRqaI16T5JjoMBOOaGUp829qgBAnNKtXuW4MB7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});